// Generated by CoffeeScript 1.6.2
(function() {
  var DivJS, root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.Number.prototype.div = function(divisor) {
    if (Number(divisor)) {
      return Math.round(this / divisor - 0.5);
    } else {
      throw "Exception: unknown divisor.";
    }
  };

  root.Number.prototype.mod = function(moderator) {
    if (Number(moderator)) {
      return Math.floor(this) % Math.floor(moderator);
    } else {
      throw "Exception: unknown divisor.";
    }
  };

  root.Math.div = function(a, b) {
    if (Number(a) && Number(b)) {
      return Number(a).div(b);
    } else {
      throw "Exception: unknown arguments type.";
    }
  };

  root.Math.mod = function(a, b) {
    if (Number(a) && Number(b)) {
      return Number(a).mod(b);
    } else {
      throw "Exception: unknown arguments type.";
    }
  };

  DivJS = (function() {
    function DivJS() {}

    DivJS.prototype.version = "0.1.0";

    return DivJS;

  })();

  root.divjs = new DivJS();

  if (typeof exports !== "undefined" && exports !== null) {
    exports.divjs = new DivJS();
  }

}).call(this);
